### ISSUE TITLE
Retina display detection

### ISSUE THREAD

**Issue by jozefspisiak** [drewbrolik/Responsive-Img#2]
Hi.

I would like to submit feature request to detect retina displays, to be able to serve double resolution pictures in order to increase their sharpness on iphones and other retina devices. 

This would be in my opinion very helpful and could prove to be essential in optimizing network traffic performance on website without sacrificing the visuals. 

Thanks, keep up with the nice code.

**Comment by drewbrolik** [comment]
That's a great idea, and in fact, I'm in the process of working that in!

**Comment by jozefspisiak** [comment]
Nice to hear this :) looking forward to that.

Also it would be handy to be able to set the image quality rendered for jpegs, since 100 has double size of 90, but very little difference. However sometimes might be 100 needed. If you want I can submit the pull request, since this is easy to do this change.

**Comment by drewbrolik** [comment]
Hey, I agree that's a nice idea. I hadn't thought of that.

You can definitely submit a pull request, but if you don't want to or don't get around to it, I'll just make sure I incorporate that next time I make an update. Either way works.

Thanks for the feedback and suggestions! I appreciate it.

**Comment by drewbrolik** [comment]
Ok, retina display and displays with other pixel ratios are now taken into account, and an appropriately sized larger image get served on those displays.

I put the jpeg quality option as the "next step" on the website, as I think that's also a smart addition to the plugin.

**Comment by drewbrolik** [comment]
I've added the jpeg quality as an option as well.

**Comment by voodoocode** [comment]
Would it be possible to set an other jpeg quality option for the retina images, than for the "normal" screen images?

This question is based on the fact, that retina images can have a lower quality, but still will look good because "the jpeg compression is harder to discern with the eye" as stated e.g. here:
http://alidark.com/responsive-retina-image-mobile/

**Comment by drewbrolik** [comment]
That's great reasoning.

Right now, for retina images, it just uses a larger version of the same image. As far as the plugin is concerned, there's no difference between a 1600 pixel image on a non-retina screen and a 400 pixel image on retina. It uses the same image for both of those scenarios.

This is something to think about, though. Could make sense to make some adjustments in the future.
