### ISSUE TITLE
Support for css background images

### ISSUE THREAD

**Issue by reblutus** [drewbrolik/Responsive-Img#3]
I noticed that your library only support img tags. Are you planning to add this to css background images?

**Comment by drewbrolik** [comment]
I would definitely consider that if enough people want it.

The reason I haven't done it yet is that it might be fairly complex, and I thought it'd be smarter to keep the plugin simple.

I do see a use for switching background images, though, and if you're saying you'd be interested in something like that, I'd look into building it in.

**Comment by reblutus** [comment]
I think it would be a good idea because background images are often much larger than "in page" images. Indeed by looking at your code, you would need to refactor quite a bit. I will look into the details and submit you something later.
